- hosts: all
  become: yes
  tasks:
  - name: Ensure firewalld is disabled and stopped
    systemd:
      name: firewalld
      enabled: no
      state: stopped
  # Set ip forwarding on in /proc and do not reload the sysctl file
  #- sysctl:
  #    name: net.bridge.bridge-nf-call-ip6tables
  #    value: 1
  #    sysctl_set: yes
  # Set ip forwarding on in /proc and do not reload the sysctl file
  #- sysctl:
  #    name: net.bridge.bridge-nf-call-iptables
  #    value: 1
  #    sysctl_set: yes
  - lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward = 1'
  - lineinfile:
      path: /etc/sysctl.conf
      line: 'net.bridge.bridge-nf-call-iptables = 1'
  - lineinfile:
      path: /etc/sysctl.conf
      line: 'net.bridge.bridge-nf-call-ip6tables = 1'
  # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  - name: Set up IP Forwarding.
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
  # This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
  - name: Ensure SELINUX is set to permissive mode.
    shell: "setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"
  - name: Adding kubernetes repository
    yum_repository:
      name: kubernetes
      description: Google Cloud Kubernetes Repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      state: present
      #exclude: kube*
  - name: Installing possibly optional packages. Please check the list.
    yum:
      name: ['bind-utils', 'unzip', 'wget', 'git', 'vim-common', 'bash-completion']
      state: present
  # Add a line to a file if it does not exist, without passing regexp
  - lineinfile:
      path: ~/.bashrc
      line: 'source <(kubectl completion bash)'
  - name: Installing required packages for docker.
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
      state: present
  - name: Adding Docker Repository.
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes
  - name: Installing docker and kubernetes packages.
    yum:
      name: ['docker-ce-18.06.1.ce', 'kubelet', 'kubeadm', 'kubectl', 'ntp']
      state: latest
  - name: Enable service docker-ce and ensure it is started
    systemd:
      name: docker
      enabled: yes
      state: started
  - name: Enable service kubelet and ensure it is started
    systemd:
      name: kubelet
      enabled: yes
      state: started
  - name: Make Sure Services are enabled at boot.
    service: name={{item}} state=started enabled=yes
    with_items:
      - docker
      - kubelet
